name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_hybrid:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libxkbcommon-dev libwayland-dev wayland-protocols libpango1.0-dev libdbus-1-dev
    - name: Build
      run: cargo check --verbose
  
  build_pure:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libxkbcommon-dev libwayland-dev wayland-protocols libpango1.0-dev libdbus-1-dev libxcursor libxfixes libxinerama
    - name: Build
      run: CFLTK_WAYLAND_ONLY=1 cargo check --verbose
