name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_hybrid:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
    - name: Build
      run: cargo build --verbose
  
