name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: |
          pkg install -y gedit cmake clang
        run: |
          git clone https://github.com/fltk-rs/fltk-rs --recurse-submodules
          cd fltk-rs
          C_INCLUDE_PATH=/usr/local/include CPLUS_INCLUDE_PATH=/usr/local/include cargo build --example paint
